spring:
  application:
    name: zuul

server:
  port: 8011

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


ribbon:
  ReadTimeout: 60000